### ISSUE TITLE
New scan

### ISSUE THREAD

**Issue by ghost** [GameTechDev/FaceMapping#1]
Hi,

I am interested in using R200 RealSense camera for 3D scanning of the face. I downloaded your code and build the exe file, however when I click on the New Scan button nothing happens. Is there any known issue in that functionality?

I appreciate your help.

**Comment by wheresthecode** [comment]
Hi changizi,

To do new scans you need to have an F200 or SR300 camera; these are the user facing cameras that have the same form factor as most webcams. The sample doesn't support R200 (the R200 is the camera that goes on the back of tablets).

Hope this helps!

-Joe

**Comment by harlanc** [comment]
When I use f200,also nothing happens...why?
