### ISSUE TITLE
SR300

### ISSUE THREAD

**Issue by ge53** [GameTechDev/FaceMapping#2]
When I run this (windows 10, rs 300 camera) I am unable to perform a new scan/can only use .obj provided or other i load in...the error message is "error set configuration 503"...any suggestions? thanks.

**Comment by ph0b** [comment]
I've had this issue before - doing sm->Init() before calling SetConfiguration() in GameFaceScan.cpp fixed it for me, as in here: https://github.com/ph0b/FaceMapping2/commit/b213b90604da9224adf9e6c30084d8aa2bc4f25f?w=1 
Btw there is a newer version of this sample: https://github.com/GameTechDev/FaceMapping2/
